- docs/DeveloperGuide.md
**DeveloperGuide.md**
- Added target user profile, value proposition and user stories
- Added user cases
- Added non-functional requirements
- Added glossary terms
> Update developer guide for user requirements

- src/main/java/seedu/guestnote/logic/commands/ListCommand.java
Modified list command. 
It is now able to: 
1. show an message indicating "No guests present" when the guest list is empty
2. show guest name and guest room number 
To do in the future:
1. Add guest ID once guest ID are all implemented
2. Pretty UI
> Modify List command

- src/main/java/seedu/guestnote/logic/commands/ListCommand.java
Updated List Command and fix test cases issues
> Update ListCommand testcases

- src/main/java/seedu/guestnote/model/guest/Guest.java
- src/main/java/seedu/guestnote/model/guest/StayDuration.java
- src/test/java/seedu/guestnote/model/guest/CheckInTest.java
- src/test/java/seedu/guestnote/model/guest/CheckOutTest.java
- src/test/java/seedu/guestnote/model/guest/GuestTest.java
- src/test/java/seedu/guestnote/model/guest/StayDurationTest.java
- Modify guest constraints to be unique phone number and email
- Added test cases for check-in/check-out/stay duration for better code coverage
> Modify unique guest constraints

- build.gradle
In this PR:
1. Enable Assertions by adding flag on `build.gradle`
2. Update name of shadowJar to be `guessnote.jar`
> Update shadowJar and enable assertions

- src/main/java/seedu/guestnote/logic/Messages.java
- src/main/java/seedu/guestnote/logic/commands/CheckInCommand.java
- src/main/java/seedu/guestnote/logic/commands/CheckOutCommand.java
- src/main/java/seedu/guestnote/logic/commands/EditCommand.java
- src/main/java/seedu/guestnote/logic/parser/AddCommandParser.java
- src/main/java/seedu/guestnote/model/guest/Guest.java
- src/main/java/seedu/guestnote/model/guest/Phone.java
- src/main/java/seedu/guestnote/storage/JsonAdaptedGuest.java
- src/main/java/seedu/guestnote/ui/GuestCard.java
- src/test/data/JsonSerializableGuestBookTest/typicalGuestsGuestBook.json
- src/test/java/seedu/guestnote/logic/commands/AddCommandTest.java
- src/test/java/seedu/guestnote/logic/commands/EditCommandTest.java
- src/test/java/seedu/guestnote/model/guest/GuestTest.java
- src/test/java/seedu/guestnote/model/guest/PhoneTest.java
- src/test/java/seedu/guestnote/storage/JsonAdaptedGuestTest.java
- src/test/java/seedu/guestnote/testutil/EditGuestDescriptorBuilder.java
- src/test/java/seedu/guestnote/testutil/GuestBuilder.java
- src/test/java/seedu/guestnote/testutil/GuestUtil.java
- src/test/java/seedu/guestnote/testutil/TypicalGuests.java
- src/test/java/seedu/guestnote/testutil/TypicalIndexes.java
This PR introduces the ability to handle an optional phone number (/p) in both AddCommand and EditCommand. Initially, users are required to provide a phone number when adding a new guest. With this PR, users can add guests without specifying their phone number. 
1. AddCommand
•	Updated the AddCommandParser to make the phone number field (/p) optional when adding a guest.
•	If the /p field is omitted, the phone number is set to null (or an empty string, depending on the default behavior you prefer).
•	Handled the case where a guest is added without a phone number and ensured that the command does not fail.
2. EditCommand
•	Updated the EditCommand to support adding a phone number if it was initially missing.
•	Handled the case where an existing guest had a missing phone number and allowed …
> Allow Optional Phone Field for AddCommand and EditCommand

- src/main/java/seedu/guestnote/logic/commands/CheckInCommand.java
- src/main/java/seedu/guestnote/logic/commands/CheckOutCommand.java
- src/main/java/seedu/guestnote/logic/parser/AddCommandParser.java
- src/main/java/seedu/guestnote/model/guest/Status.java
- src/main/java/seedu/guestnote/model/util/SampleDataUtil.java
- src/main/java/seedu/guestnote/ui/GuestCard.java
- src/test/data/JsonGuestBookStorageTest/invalidAndValidGuestGuestBook.json
- src/test/data/JsonGuestBookStorageTest/invalidGuestGuestBook.json
- src/test/data/JsonSerializableGuestBookTest/duplicateGuestGuestBook.json
- src/test/data/JsonSerializableGuestBookTest/invalidGuestGuestBook.json
- src/test/data/JsonSerializableGuestBookTest/typicalGuestsGuestBook.json
- src/test/java/seedu/guestnote/logic/commands/CheckOutCommandTest.java
- src/test/java/seedu/guestnote/logic/commands/CommandTestUtil.java
- src/test/java/seedu/guestnote/model/guest/StatusTest.java
- src/test/java/seedu/guestnote/testutil/GuestBuilder.java
- src/test/java/seedu/guestnote/testutil/TypicalGuests.java
Bug fixes:
- Remove updating of guest list view (ie resetting of guest list view to default) after check-in / check-out of specific guest, so that view remains on current filtered view
Refactoring:
- Refactor default `BOOKING` status to `BOOKED` so as to align with other naming patterns `CHECKED-IN` and `CHECKED-OUT` 
**please dont merge first cos im trying to fulfill parallel pr**
> Fix guest list display after check-in / check-out command

- src/main/java/seedu/guestnote/model/guest/FieldContainsKeywordsPredicate.java
- src/test/java/seedu/guestnote/model/guest/AnyFieldContainsKeywordsPredicateTest.java
- src/test/java/seedu/guestnote/model/guest/FieldContainsKeywordsPredicateTest.java
Fix bugs of FIndCommand listing guests with partial match.
> Fix findcommand bug

- src/test/java/seedu/guestnote/model/guest/AnyFieldContainsKeywordsPredicateTest.java
- src/test/java/seedu/guestnote/model/guest/FieldContainsKeywordsPredicateTest.java
Add new test cases to ensure find command does not list out guests with partial matches
> Add test cases for findcommad

- src/main/java/seedu/guestnote/logic/commands/CheckInCommand.java
- src/main/java/seedu/guestnote/logic/commands/CheckOutCommand.java
- src/main/java/seedu/guestnote/logic/commands/StatusChangeCommand.java
- Included new abstract class for both check-in and check-out classes to inherit from
> Refactor check-in and check-out classes to inherit from abstract class

- docs/diagrams/CommitActivityDiagram.puml
- docs/diagrams/ModelClassDiagram.puml
- docs/diagrams/ParserClasses.puml
Updated UML diagrams in the following files:
CommitActivityDiagram.puml
ModelClassDiagram.puml
ParserClasses.puml
> Update UMl diagrams

- docs/DeveloperGuide.md
Update DG to ensure "Use case ends." is added at the back of every extension.
> Fix inconsistency in DG

- docs/UserGuide.md
- docs/package-lock.json
- docs/package.json
Fix bug due to indents caused misread in UG
> Fix indent-related issues in UG

- docs/DeveloperGuide.md
- docs/diagrams/BetterModelClassDiagram.puml
- docs/diagrams/StorageClassDiagram.puml
- Refactor some of the UML diagrams
- Added use cases for check-in and check-out of guest in developer guide
> Refactor Developer Guide

- docs/DeveloperGuide.md
- Update Glossary section (will be further updated to remove unnecessary keyworkds)
- Update Appendix: Instructions for manual testing
- Close #167
> Update DG's Glossary and Appendix

- src/main/java/seedu/guestnote/ui/GuestCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/GuestListCard.fxml
- src/main/resources/view/LightTheme.css
- Fix underscore in status label (replace with space)
- Fix readability issue on red color
- Shift status label to right of name
> Fix status UI display

- docs/DeveloperGuide.md
- docs/diagrams/ModelClassDiagram.puml
Correcting errors, polishing, as well as formatting the previous iteration of the DG.
Wrote the Implementation section that spells out the main new features implemented. 
Did not manage to look through Test Section properly (only managed to format it).
Planned Enhancements is left empty for now until futher thought is put by the group.
> Update DG [Latest]

- src/main/java/seedu/guestnote/logic/parser/AddCommandParser.java
- src/test/java/seedu/guestnote/logic/commands/CommandTestUtil.java
- src/test/java/seedu/guestnote/logic/commands/EditCommandTest.java
- src/test/java/seedu/guestnote/logic/commands/EditGuestDescriptorTest.java
- src/test/java/seedu/guestnote/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/guestnote/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/guestnote/model/GuestNoteTest.java
- src/test/java/seedu/guestnote/model/guest/GuestTest.java
- src/test/java/seedu/guestnote/model/guest/UniqueGuestListTest.java
- src/test/java/seedu/guestnote/testutil/TypicalGuests.java
Fix bug where duplicate requests in add did not show error
> Merge duplicate add req error

- src/main/java/seedu/guestnote/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/guestnote/logic/parser/ParserUtil.java
- src/test/java/seedu/guestnote/logic/parser/DeleteCommandParserTest.java
- Close #157 #158 #159 
- More specific error messages when invalid index, index has leading zeroes or index too large
> Fix Delete Command Parsing with large or unusual integers

- README.md
- docs/DeveloperGuide.md
- src/main/java/seedu/guestnote/commons/core/GuiSettings.java
- src/main/java/seedu/guestnote/ui/MainWindow.java
- Retain theme preference upon startup
- Fix broken links in README.md
- Closes #147
> Fix bugs In README.md and FXML

- src/main/java/seedu/guestnote/logic/parser/CliSyntax.java
- src/main/java/seedu/guestnote/model/guest/Name.java
- src/test/java/seedu/guestnote/logic/parser/ParserUtilTest.java
- src/test/java/seedu/guestnote/model/guest/NameTest.java
- src/test/java/seedu/guestnote/storage/JsonAdaptedGuestTest.java
- Allow names to contain additional special characters `- @ / () , '`
- change cli syntax prefix to be `\` instead of `/`
> Change Name Constraints

- src/main/resources/view/DarkTheme.css
- src/main/resources/view/LightTheme.css
> Fixed bug of shifting text and scroll issue

- docs/DeveloperGuide.md
In this PR, I added future enhancements to the DG that will guard against PE bugs:
1. Future restriction on having multiple guests in one room
2. Future restriction on guests having the same email and phone
I also added more extensions to the check in use case, which i accidentally left out.
> Update DG II

- src/main/java/seedu/guestnote/logic/parser/ParserUtil.java
- src/main/java/seedu/guestnote/model/guest/Email.java
- predomain field can now support underscores
- email field is now case insensitive
> Change Email Constraints

- src/main/java/seedu/guestnote/logic/parser/ListCommandParser.java
> Fix list command not using new prefix

- docs/DeveloperGuide.md
In this PR, I made changes to polish the DG, including
1. Spelling errors
2. Fixing unclear sentences
3. Fixing the Use cases, where there were bugs in terms of numbering or extensions
4. Fixing the test cases, where there were bugs previously in terms of expected behavior.
5. Removing Address Book which still existed.
6. Fix any found formatting issues
> Final DG Submission

- docs/DeveloperGuide.md
In this PR, I added line breaks where necessary for formatting and changed plural to singular for `preconditions`.
> DG Final Update
